import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, Copy, Check, RefreshCw, Youtube } from "lucide-react";
import { api, type SocialCopy } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";

interface Props {
  postId: string;
  title: string;
  open: boolean;
  onOpenChange: (v: boolean) => void;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <Button
      size="sm" variant="outline"
      className="h-6 text-[10px] gap-1 px-2"
      onClick={() => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }}
    >
      {copied ? <Check className="h-3 w-3 text-success" /> : <Copy className="h-3 w-3" />}
      {copied ? "Copied" : "Copy"}
    </Button>
  );
}

export function SocialCopyDialog({ postId, title, open, onOpenChange }: Props) {
  const [data, setData] = useState<SocialCopy | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (!open || !postId) return;
    setLoading(true);
    api.getSocialCopy(postId)
      .then((r) => setData(r))
      .catch(() => setData({ exists: false }))
      .finally(() => setLoading(false));
  }, [open, postId]);

  const generate = async () => {
    setGenerating(true);
    try {
      const r = await api.generateSocialCopy(postId);
      setData(r);
      toast({ title: "Social copy generated" });
    } catch (e: any) {
      toast({ title: "Generation failed", description: e.message, variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-sm">Social Copy — {title}</DialogTitle>
          <DialogDescription className="text-xs">
            Titles, captions & hashtags generated by your configured AI provider. Click Copy on any field.
          </DialogDescription>
        </DialogHeader>

        <div className="flex items-center justify-between gap-2 pb-2 border-b border-border">
          <div className="text-[10px] text-muted-foreground">
            {data?.exists && data.provider ? (
              <>Generated with <code>{data.provider}</code> · {data.model}</>
            ) : (
              "Nothing generated yet for this post."
            )}
          </div>
          <Button size="sm" onClick={generate} disabled={generating} className="gap-1">
            {generating ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
            {data?.exists ? "Regenerate" : "Generate"}
          </Button>
        </div>

        {loading && <div className="py-8 flex justify-center"><Loader2 className="h-5 w-5 animate-spin" /></div>}

        {!loading && data?.exists && (
          <div className="space-y-4 pt-2 text-xs">
            {data.youtube && (
              <section className="space-y-2">
                <div className="flex items-center gap-2">
                  <Youtube className="h-4 w-4 text-[#ff0000]" />
                  <h4 className="font-semibold">YouTube Shorts</h4>
                </div>
                {data.youtube.titles?.map((t, i) => (
                  <div key={i} className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Title {i + 1}</Badge>
                    <span className="flex-1 leading-snug">{t}</span>
                    <CopyButton text={t} />
                  </div>
                ))}
                {data.youtube.description && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Description</Badge>
                    <pre className="flex-1 whitespace-pre-wrap leading-snug font-sans">{data.youtube.description}</pre>
                    <CopyButton text={data.youtube.description} />
                  </div>
                )}
                {data.youtube.tags && data.youtube.tags.length > 0 && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Tags</Badge>
                    <div className="flex-1 flex flex-wrap gap-1">
                      {data.youtube.tags.map((t) => <Badge key={t} variant="secondary" className="text-[9px]">{t}</Badge>)}
                    </div>
                    <CopyButton text={data.youtube.tags.join(", ")} />
                  </div>
                )}
              </section>
            )}

            {data.tiktok && (
              <section className="space-y-2">
                <h4 className="font-semibold">TikTok</h4>
                {data.tiktok.caption && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Caption</Badge>
                    <pre className="flex-1 whitespace-pre-wrap leading-snug font-sans">{data.tiktok.caption}</pre>
                    <CopyButton text={data.tiktok.caption} />
                  </div>
                )}
                {data.tiktok.hashtags && data.tiktok.hashtags.length > 0 && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Hashtags</Badge>
                    <div className="flex-1 flex flex-wrap gap-1">
                      {data.tiktok.hashtags.map((h) => <Badge key={h} variant="secondary" className="text-[9px]">{h}</Badge>)}
                    </div>
                    <CopyButton text={data.tiktok.hashtags.join(" ")} />
                  </div>
                )}
              </section>
            )}

            {data.instagram && (
              <section className="space-y-2">
                <h4 className="font-semibold">Instagram Reels</h4>
                {data.instagram.caption && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Caption</Badge>
                    <pre className="flex-1 whitespace-pre-wrap leading-snug font-sans">{data.instagram.caption}</pre>
                    <CopyButton text={data.instagram.caption} />
                  </div>
                )}
                {data.instagram.hashtags && data.instagram.hashtags.length > 0 && (
                  <div className="flex items-start gap-2 bg-secondary/40 rounded p-2">
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">Hashtags</Badge>
                    <div className="flex-1 flex flex-wrap gap-1">
                      {data.instagram.hashtags.map((h) => <Badge key={h} variant="secondary" className="text-[9px]">{h}</Badge>)}
                    </div>
                    <CopyButton text={data.instagram.hashtags.join(" ")} />
                  </div>
                )}
              </section>
            )}

            {data.benchmarks_used && data.benchmarks_used.length > 0 && (
              <section className="space-y-1.5 pt-3 border-t border-border/60">
                <div className="flex items-center gap-2">
                  <Youtube className="h-3.5 w-3.5 text-[#ff0000]" />
                  <h4 className="font-semibold text-[11px]">Style references</h4>
                  <span className="text-[10px] text-muted-foreground">
                    ({data.benchmarks_used.length} high-performing videos{data.subreddit ? ` in r/${data.subreddit}` : ""})
                  </span>
                </div>
                <p className="text-[10px] text-muted-foreground leading-snug">
                  These videos informed the hook phrasing, tag patterns, and tone above.
                  Click to open on YouTube.
                </p>
                <div className="space-y-1">
                  {data.benchmarks_used.map((b) => (
                    <a
                      key={b.video_id}
                      href={`https://www.youtube.com/watch?v=${b.video_id}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-[10px] bg-secondary/30 hover:bg-secondary/60 rounded px-2 py-1 transition-colors"
                    >
                      <Badge variant="outline" className="text-[9px] px-1.5 py-0 font-mono shrink-0">
                        {b.view_count >= 1_000_000
                          ? `${(b.view_count / 1_000_000).toFixed(1)}M`
                          : b.view_count >= 1_000
                          ? `${(b.view_count / 1_000).toFixed(0)}K`
                          : b.view_count}
                      </Badge>
                      <span className="flex-1 truncate">{b.title}</span>
                      <span className="text-muted-foreground shrink-0 max-w-[30%] truncate">{b.channel}</span>
                    </a>
                  ))}
                </div>
              </section>
            )}
          </div>
        )}

        {!loading && !data?.exists && (
          <p className="text-xs text-muted-foreground text-center py-6">
            Click <strong>Generate</strong> to create YouTube / TikTok / Instagram copy for this post.
          </p>
        )}
      </DialogContent>
    </Dialog>
  );
}
